/* Copyright 2023 The MathWorks, Inc. */
#ifndef VDBVOLUMEBUILTIN_UTIL_HPP
#define VDBVOLUMEBUILTIN_UTIL_HPP

#include "package.h"

#ifdef BUILDING_LIBMWVDBVOLUMEBUILTIN

/* This header is being included by files inside this module */

#define VDBVOLUMEBUILTIN_EXPORT_CLASS DLL_EXPORT_SYM
#define VDBVOLUMEBUILTIN_EXPORT_FRIEND DLL_EXPORT_SYM
#define VDBVOLUMEBUILTIN_EXPORT_FCN DLL_EXPORT_SYM
#define VDBVOLUMEBUILTIN_EXPORT_TEMPLATE DLL_EXPORT_TEMPLATE

#define VDBVOLUMEBUILTIN_EXPORT_EXTERN_C extern "C" DLL_EXPORT_SYM

#define VDBVOLUMEBUILTIN_EXPORT_VAR extern
#define VDBVOLUMEBUILTIN_EXPORT_VAR_DEF DLL_EXPORT_SYM

#define VDBVOLUMEBUILTIN_EXPORT DLL_EXPORT_SYM

#else

/* This file is being include by other TMW internal modules */
#define VDBVOLUMEBUILTIN_EXPORT_CLASS DLL_IMPORT_SYM
#define VDBVOLUMEBUILTIN_EXPORT_FRIEND DLL_IMPORT_SYM
#define VDBVOLUMEBUILTIN_EXPORT_FCN DLL_IMPORT_SYM
#define VDBVOLUMEBUILTIN_EXPORT_TEMPLATE DLL_EXPORT_TEMPLATE

#define VDBVOLUMEBUILTIN_EXPORT_EXTERN_C extern "C" DLL_IMPORT_SYM

#define VDBVOLUMEBUILTIN_EXPORT_VAR extern DLL_IMPORT_SYM

#define VDBVOLUMEBUILTIN_EXPORT DLL_IMPORT_SYM
#endif

#endif // VDBVOLUMEBUILTIN_UTIL_HPP

// EOF
